name: dmsecurity
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - django==5.1.2
      - djangorestframework==3.15.2
      - django-cors-headers==4.4.0
      - django-environ==0.11.2
      - django-extensions==3.2.3
      - django-stubs==5.0.2
      - djangorestframework-simplejwt==5.3.1
      - openai==2.6.1
