# Generated by Django 5.1.2 on 2025-10-23 16:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del riesgo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('likelihood', models.IntegerField(help_text='1=Muy improbable, 5=Muy probable', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Probabilidad')),
                ('impact', models.IntegerField(help_text='1=Insignificante, 5=Catastrófico', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Impacto')),
                ('status', models.CharField(choices=[('IDENTIFIED', 'Identificado'), ('IN_TREATMENT', 'En Tratamiento'), ('MITIGATED', 'Mitigado'), ('CLOSED', 'Cerrado')], default='IDENTIFIED', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('identified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identified_risks', to=settings.AUTH_USER_MODEL, verbose_name='Identificado por')),
            ],
            options={
                'verbose_name': 'Riesgo',
                'verbose_name_plural': 'Riesgos',
                'ordering': ['-created_at'],
            },
        ),
    ]
