# Generated by Django 5.1.2 on 2025-10-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='controls',
            field=models.ManyToManyField(blank=True, help_text='Controles de seguridad que ayudan a mitigar este riesgo', related_name='risks', to='security.security', verbose_name='Controles asociados'),
        ),
    ]
