# Generated by Django 5.1.2 on 2025-10-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('risk', '0002_risk_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='assets',
            field=models.ManyToManyField(blank=True, help_text='Activos de la organización que están relacionados con este riesgo', related_name='risks', to='assets.asset', verbose_name='Activos afectados'),
        ),
    ]
