# Generated by Django 5.1.2 on 2025-10-23 18:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del control')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('control_type', models.CharField(choices=[('PREVENTIVE', 'Preventivo'), ('DETECTIVE', 'Detectivo'), ('CORRECTIVE', 'Correctivo')], default='PREVENTIVE', max_length=20, verbose_name='Tipo de control')),
                ('effectiveness', models.IntegerField(help_text='1=Muy baja, 5=Muy alta', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Efectividad')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('UNDER_REVIEW', 'En revisión')], default='ACTIVE', max_length=20, verbose_name='Estado del control')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('implemented_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implemented_controls', to=settings.AUTH_USER_MODEL, verbose_name='Implementado por')),
            ],
            options={
                'verbose_name': 'Control de Seguridad',
                'verbose_name_plural': 'Controles de Seguridad',
                'ordering': ['-created_at'],
            },
        ),
    ]
